apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: qixiaowei-system-manage
  name: qixiaowei-system-manage
  namespace: qixiaowei-stg1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: qixiaowei-system-manage
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: qixiaowei-system-manage
    spec:
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ''
      imagePullSecrets:
        - name: harbor-deploy
      containers:
        - image: harbor.qixiaowei.net/qixiaowei-cloud-stg/qixiaowei-system-manage:latest
          name: qixiaowei-system-manage
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: 600Mi
          volumeMounts:
            - name: host-time
              readOnly: true
              mountPath: /etc/localtime
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: qixiaowei-system-manage
  name: qixiaowei-system-manage
  namespace: qixiaowei-stg1
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: qixiaowei-system-manage
  sessionAffinity: None
  type: ClusterIP