kind: pipeline
type: docker
name: qixiaowei-gateway-pipeline

steps:


  - name: scp
    pull: if-not-exists
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: host-stg
      username:
        from_secret: host-username-stg
      password:
        from_secret: host-pwd-stg
      port: 22
      command_timeout: 2m
      target: /root/deploy/
      source: ./deploy/
      rm: true
      overwrite: true

  - name: deploy
    image: appleboy/drone-ssh
    pull: if-not-exists
    settings:
      host:
        from_secret: host-stg
      username:
        from_secret: host-username-stg
      password:
        from_secret: host-pwd-stg
      port: 22
      script:
        - kubectl apply -f deploy/stg/*.yaml

volumes:
  - name: cache
    host:
      path: /tmp/cache/mvnrepo