kind: pipeline
type: docker
name: qixiaowei-cloud-prd

steps:
- name: compile
  pull: if-not-exists
  image: docker.io/library/maven:3.8.6
  volumes:
    - name: cache
      path: /root/.m2
  commands:
    - mvn clean package -Pprod -DskipTests=true -pl !qixiaowei-gen
  depends_on:
    - clone

- name: build-qixiaowei-gateway
  pull: if-not-exists
  image: plugins/docker
  settings:
    registry: harbor.qixiaowei.net
    username: deploy
    password:
      from_secret: deploy-pwd
    insecure: true
    repo: harbor.qixiaowei.net/qixiaowei-cloud/qixiaowei-gateway
    dockerfile: qixiaowei-gateway/Dockerfile
    tags:
      - v1.0.0
  depends_on:
    - compile

- name: build-qixiaowei-auth
  pull: if-not-exists
  image: plugins/docker
  settings:
    registry: harbor.qixiaowei.net
    username: deploy
    password:
      from_secret: deploy-pwd
    insecure: true
    repo: harbor.qixiaowei.net/qixiaowei-cloud/qixiaowei-auth
    dockerfile: qixiaowei-auth/Dockerfile
    tags:
      - v1.0.0
  depends_on:
    - compile

- name: build-qixiaowei-system-manage
  pull: if-not-exists
  image: plugins/docker
  settings:
    registry: harbor.qixiaowei.net
    username: deploy
    password:
      from_secret: deploy-pwd
    insecure: true
    repo: harbor.qixiaowei.net/qixiaowei-cloud/qixiaowei-system-manage
    dockerfile: qixiaowei-service/qixiaowei-system-manage/Dockerfile
    tags:
      - v1.0.0
  depends_on:
    - compile

- name: build-qixiaowei-operate-cloud
  pull: if-not-exists
  image: plugins/docker
  settings:
    registry: harbor.qixiaowei.net
    username: deploy
    password:
      from_secret: deploy-pwd
    insecure: true
    repo: harbor.qixiaowei.net/qixiaowei-cloud/qixiaowei-operate-cloud
    dockerfile: qixiaowei-service/qixiaowei-operate-cloud/Dockerfile
    tags:
      - v1.0.0
  depends_on:
    - compile

- name: build-qixiaowei-file
  pull: if-not-exists
  image: plugins/docker
  settings:
    registry: harbor.qixiaowei.net
    username: deploy
    password:
      from_secret: deploy-pwd
    insecure: true
    repo: harbor.qixiaowei.net/qixiaowei-cloud/qixiaowei-file
    dockerfile: qixiaowei-service/qixiaowei-file/Dockerfile
    tags:
      - v1.0.0
  depends_on:
    - compile

- name: scp
  pull: if-not-exists
  image: appleboy/drone-scp
  settings:
    host:
      from_secret: host
    username:
      from_secret: host-username
    password:
      from_secret: host-pwd
    port: 12205
    command_timeout: 2m
    target: /root/k8s/qxw/
    source: ./deploy/
    rm: true
    overwrite: true
  depends_on:
    - build-qixiaowei-gateway
    - build-qixiaowei-auth
    - build-qixiaowei-system-manage
    - build-qixiaowei-operate-cloud
    - build-qixiaowei-file

- name: deploy
  pull: if-not-exists
  image: appleboy/drone-ssh
  settings:
    host:
      from_secret: host
    username:
      from_secret: host-username
    password:
      from_secret: host-pwd
    port: 12205
    script:
      - kubectl apply -k k8s/qxw/deploy/prd/
  depends_on:
    - scp

volumes:
  - name: cache
    host:
      path: /tmp/cache/mvnrepo
