kind: pipeline
type: docker
name: qixiaowei-gateway-pipeline

steps:


  - name: deploy
    image: appleboy/drone-ssh
    pull: if-not-exists
    settings:
      host:
        from_secret: host-stg
      username:
        from_secret: host-username-stg
      password:
        from_secret: host-pwd-stg
      port: 22
      script:
        - kubectl apply -f deploy/stg/qixiaowei-gateway.yaml

volumes:
  - name: cache
    host:
      path: /tmp/cache/mvnrepo