kind: pipeline
type: docker
name: qixiaowei-gateway-pipeline

steps:
- name: compile
  pull: if-not-exists
  image: docker.io/library/maven:3.8.6
  volumes:
    - name: cache
      path: /root/.m2
  commands:
  - mvn clean package -Ptest -DskipTests=true -pl !qixiaowei-gen

- name: build-qixiaowei-gateway
  pull: if-not-exists
  image: plugins/docker
  settings:
    registry: harbor.qixiaowei.net
    username: deploy
    password:
      from_secret: deploy-pwd
    insecure: true
    repo: harbor.qixiaowei.net/qixiaowei-cloud-stg/qixiaowei-gateway
    dockerfile: qixiaowei-gateway/Dockerfile
    tags:
      - latest

- name: build-qixiaowei-auth
  pull: if-not-exists
  image: plugins/docker
  settings:
    registry: harbor.qixiaowei.net
    username: deploy
    password:
      from_secret: deploy-pwd
    insecure: true
    repo: harbor.qixiaowei.net/qixiaowei-cloud-stg/qixiaowei-auth
    dockerfile: qixiaowei-auth/Dockerfile
    tags:
      - latest

- name: scp
  pull: if-not-exists
  image: appleboy/drone-scp
  settings:
    host:
      from_secret: host-stg
    username:
      from_secret: host-username-stg
    password:
      from_secret: host-pwd-stg
    port: 22
    command_timeout: 2m
    target: /root/k8s/
    source: ./deploy/
    rm: true
    overwrite: true
    depends_on:
    - build-qixiaowei-gateway
    - build-qixiaowei-auth

- name: deploy
  pull: if-not-exists
  image: appleboy/drone-ssh
  settings:
    host:
      from_secret: host-stg
    username:
      from_secret: host-username-stg
    password:
      from_secret: host-pwd-stg
    port: 22
    script:
      - kubectl apply -f k8s/deploy/stg/*.yaml
    depends_on:
    - build-qixiaowei-gateway
    - build-qixiaowei-auth

volumes:
  - name: cache
    host:
      path: /tmp/cache/mvnrepo
