kind: pipeline
type: docker
name: qixiaowei-cloud-pipeline

steps:
  - name: compile
    pull: if-not-exists
    image: maven:3-jdk-8
    volumes:
      - name: cache
        path: /root/.m2
    commands:
      - mvn clean package -Ptest -DskipTests=true
      - ls /root/.m2/

volumes:
  - name: cache
    host:
      path: /tmp/cache