pipeline:
  compile:
    image: maven:3-jdk-8
    volumes:
      - name: maven-repo
        path: /root/.m2
    commands:
      - mvn clean package -Ptest -DskipTests=true

  build:
    image: plugins/docker
    settings:
      registry: harbor.qixiaowei.net
      username:
        from_secret: username
      password:
        from_secret: password
      insecure: true
      repo: harbor.qixiaowei.net/qixiaowei-cloud/qixiaowei-file
      dockerfile: qixiaowei-service/qixiaowei-file/Dockerfile
      tags:
        - ${DRONE_BUILD_NUMBER}
    trigger:
      status:
        - success

    depends_on:
      - compile

volumes:
  - name: maven-repo
    host:
      path: /tmp/mavenrepo
