kind: pipeline
type: kubernetes
name: qixiaowei-gateway-pipeline

steps:
  - name: compile
    pull: if-not-exists
    image: docker.io/library/maven:3.8.6
    volumes:
      - name: cache
        path: /root/.m2
    commands:
      - mvn clean package -Ptest -DskipTests=true -pl !qixiaowei-gen

volumes:
  - name: cache
    host:
      path: /tmp/cache/mvnrepo