kind: pipeline
type: docker
name: qixiaowei-cloud-pipeline

steps:
  - name: compile
    pull: if-not-exists
    image: maven:3-jdk-8
    commands:
      - mvn version
      - mvn clean
      - ls /root/.m2