kind: pipeline
type: docker
name: qixiaowei-cloud-compile

steps:
  - name: compile
    pull: if-not-exists
    image: maven:3-jdk-8
    volumes:
      - name: mavenrepo
        path: /root/.m2
    commands:
      - mvn clean package -Ptest -DskipTests=true

volumes:
  - name: mavenrepo
    host:
      path: /tmp/mavenrepo

---
kind: pipeline
type: docker
name: build-qixiaowei-file-image

steps:
  - name: build-qixiaowei-file-image
    pull: if-not-exists
    image: plugins/docker
    settings:
      registry: harbor.qixiaowei.net
      username:
        from_secret: username
      password:
        from_secret: password
      insecure: true
      repo: harbor.qixiaowei.net/qixiaowei-cloud/qixiaowei-file
      dockerfile: qixiaowei-service/qixiaowei-file/Dockerfile
      tags:
        - latest
    trigger:
      status:
        - success
    depends_on:
      qixiaowei-cloud-compile

---
kind: pipeline
type: docker
name: build-qixiaowei-auth-image

steps:
  - name: build-qixiaowei-auth-image
    pull: if-not-exists
    image: plugins/docker
    settings:
      registry: harbor.qixiaowei.net
      username:
        from_secret: username
      password:
        from_secret: password
      insecure: true
      repo: harbor.qixiaowei.net/qixiaowei-cloud/qixiaowei-auth
      dockerfile: qixiaowei-auth/Dockerfile
      tags:
        - latest
    trigger:
      status:
        - success
    depends_on:
      qixiaowei-cloud-compile