kind: pipeline
type: docker
name: qixiaowei-cloud-stg

steps:
  - name: compile
    pull: if-not-exists
    image: docker.io/library/maven:3.8.6
    volumes:
      - name: cache
        path: /root/.m2
    commands:
      - mvn -pl !qixiaowei-gen clean package -Ptest -DskipTests

volumes:
  - name: cache
    host:
      path: /tmp/cache/mvnrepo