kind: pipeline
type: docker
name: qixiaowei-cloud-stg

steps:
  - name: compile
    pull: if-not-exists
    image: docker.io/library/maven:3.8.6
    volumes:
      - name: cache
        path: /root/.m2
    commands:
      - mvn clean package -Ptest -DskipTests -pl !qixiaowei-gen

  - name: builid qixiaowei-file image
    pull: if-not-exists
    image: plugins/docker
    settings:
      registry: harbor.qixiaowei.net
      username: deploy
      password:
        from_secret: deploy-pwd
      insecure: true
      repo: harbor.qixiaowei.net/qixiaowei-cloud/qixiaowei-file
      dockerfile: qixiaowei-service/qixiaowei-file/Dockerfile
      tags:
        - v-1.0.${DRONE_BUILD_NUMBER}

volumes:
  - name: cache
    host:
      path: /tmp/cache/mvnrepo