kind: pipeline
type: docker
name: qixiaowei-cloud-pipeline

steps:
  - name: restore-cache
    pull: if-not-exists
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./.m2/

  - name: compile
    pull: if-not-exists
    image: maven:3-jdk-8
    volumes:
      - name: mavenrepo
        path: /root/.m2
    commands:
      - mvn clean package -Ptest -DskipTests=true

  - name: rebuild-cache
    pull: if-not-exists
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./.m2/

volumes:
  - name: cache
    host:
      path: /tmp/cache
  - name: mavenrepo
    host:
      path: /tmp/mavenrepo