USE `operate_cloud`;
SET NAMES utf8mb4;

-- ----------------------------
-- initialization data
-- ----------------------------

-- ----------------------------
-- init of salary_item
-- ----------------------------
INSERT INTO `salary_item`(`salary_item_id`, `first_level_item`, `second_level_item`, `third_level_item`, `scope`, `sort`, `delete_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (1, 1, 1, '基本工资', 1, 1, 0, 0, sysdate(), 0, sysdate());
INSERT INTO `salary_item`(`salary_item_id`, `first_level_item`, `second_level_item`, `third_level_item`, `scope`, `sort`, `delete_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (2, 1, 1, '计件工资', 1, 2, 0, 0, sysdate(), 0, sysdate());
INSERT INTO `salary_item`(`salary_item_id`, `first_level_item`, `second_level_item`, `third_level_item`, `scope`, `sort`, `delete_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (3, 1, 1, '平时加班', 1, 3, 0, 0, sysdate(), 0, sysdate());
INSERT INTO `salary_item`(`salary_item_id`, `first_level_item`, `second_level_item`, `third_level_item`, `scope`, `sort`, `delete_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (4, 1, 1, '周末加班', 1, 4, 0, 0, sysdate(), 0, sysdate());
INSERT INTO `salary_item`(`salary_item_id`, `first_level_item`, `second_level_item`, `third_level_item`, `scope`, `sort`, `delete_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (5, 1, 1, '节假日加班', 1, 5, 0, 0, sysdate(), 0, sysdate());
INSERT INTO `salary_item`(`salary_item_id`, `first_level_item`, `second_level_item`, `third_level_item`, `scope`, `sort`, `delete_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (6, 1, 1, '奖励工时', 1, 6, 0, 0, sysdate(), 0, sysdate());
INSERT INTO `salary_item`(`salary_item_id`, `first_level_item`, `second_level_item`, `third_level_item`, `scope`, `sort`, `delete_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (7, 1, 1, '补时', 1, 7, 0, 0, sysdate(), 0, sysdate());
INSERT INTO `salary_item`(`salary_item_id`, `first_level_item`, `second_level_item`, `third_level_item`, `scope`, `sort`, `delete_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (8, 1, 1, '样品费', 1, 8, 0, 0, sysdate(), 0, sysdate());
INSERT INTO `salary_item`(`salary_item_id`, `first_level_item`, `second_level_item`, `third_level_item`, `scope`, `sort`, `delete_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (9, 1, 1, '支援费', 1, 9, 0, 0, sysdate(), 0, sysdate());
INSERT INTO `salary_item`(`salary_item_id`, `first_level_item`, `second_level_item`, `third_level_item`, `scope`, `sort`, `delete_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (10, 1, 1, '销售提成', 1, 10, 0, 0, sysdate(), 0, sysdate());
INSERT INTO `salary_item`(`salary_item_id`, `first_level_item`, `second_level_item`, `third_level_item`, `scope`, `sort`, `delete_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (11, 1, 1, '岗位津贴', 1, 11, 0, 0, sysdate(), 0, sysdate());
INSERT INTO `salary_item`(`salary_item_id`, `first_level_item`, `second_level_item`, `third_level_item`, `scope`, `sort`, `delete_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (12, 1, 1, '保底补贴', 1, 12, 0, 0, sysdate(), 0, sysdate());
INSERT INTO `salary_item`(`salary_item_id`, `first_level_item`, `second_level_item`, `third_level_item`, `scope`, `sort`, `delete_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (13, 1, 1, '其他工资', 1, 13, 0, 0, sysdate(), 0, sysdate());
INSERT INTO `salary_item`(`salary_item_id`, `first_level_item`, `second_level_item`, `third_level_item`, `scope`, `sort`, `delete_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (14, 1, 2, '夜班补贴', 1, 14, 0, 0, sysdate(), 0, sysdate());
INSERT INTO `salary_item`(`salary_item_id`, `first_level_item`, `second_level_item`, `third_level_item`, `scope`, `sort`, `delete_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (15, 1, 2, '岗位补贴', 1, 15, 0, 0, sysdate(), 0, sysdate());
INSERT INTO `salary_item`(`salary_item_id`, `first_level_item`, `second_level_item`, `third_level_item`, `scope`, `sort`, `delete_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (16, 1, 2, '宿舍管理员补贴', 1, 16, 0, 0, sysdate(), 0, sysdate());
INSERT INTO `salary_item`(`salary_item_id`, `first_level_item`, `second_level_item`, `third_level_item`, `scope`, `sort`, `delete_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (17, 1, 2, '灌胶补贴', 1, 17, 0, 0, sysdate(), 0, sysdate());
INSERT INTO `salary_item`(`salary_item_id`, `first_level_item`, `second_level_item`, `third_level_item`, `scope`, `sort`, `delete_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (18, 1, 2, '焊锡补贴', 1, 18, 0, 0, sysdate(), 0, sysdate());
INSERT INTO `salary_item`(`salary_item_id`, `first_level_item`, `second_level_item`, `third_level_item`, `scope`, `sort`, `delete_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (19, 1, 2, '喷焊补贴', 1, 19, 0, 0, sysdate(), 0, sysdate());
INSERT INTO `salary_item`(`salary_item_id`, `first_level_item`, `second_level_item`, `third_level_item`, `scope`, `sort`, `delete_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (20, 1, 2, '绩效津贴', 1, 20, 0, 0, sysdate(), 0, sysdate());
INSERT INTO `salary_item`(`salary_item_id`, `first_level_item`, `second_level_item`, `third_level_item`, `scope`, `sort`, `delete_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (21, 1, 2, '充电补贴', 1, 21, 0, 0, sysdate(), 0, sysdate());
INSERT INTO `salary_item`(`salary_item_id`, `first_level_item`, `second_level_item`, `third_level_item`, `scope`, `sort`, `delete_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (22, 1, 2, '文案费', 1, 22, 0, 0, sysdate(), 0, sysdate());
INSERT INTO `salary_item`(`salary_item_id`, `first_level_item`, `second_level_item`, `third_level_item`, `scope`, `sort`, `delete_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (23, 1, 2, '网管费', 1, 23, 0, 0, sysdate(), 0, sysdate());
INSERT INTO `salary_item`(`salary_item_id`, `first_level_item`, `second_level_item`, `third_level_item`, `scope`, `sort`, `delete_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (24, 1, 2, '平台维护费', 1, 24, 0, 0, sysdate(), 0, sysdate());
INSERT INTO `salary_item`(`salary_item_id`, `first_level_item`, `second_level_item`, `third_level_item`, `scope`, `sort`, `delete_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (25, 1, 2, '带班绩效', 1, 25, 0, 0, sysdate(), 0, sysdate());
INSERT INTO `salary_item`(`salary_item_id`, `first_level_item`, `second_level_item`, `third_level_item`, `scope`, `sort`, `delete_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (26, 1, 2, '买菜津贴', 1, 26, 0, 0, sysdate(), 0, sysdate());
INSERT INTO `salary_item`(`salary_item_id`, `first_level_item`, `second_level_item`, `third_level_item`, `scope`, `sort`, `delete_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (27, 1, 2, '高温补贴', 1, 27, 0, 0, sysdate(), 0, sysdate());
INSERT INTO `salary_item`(`salary_item_id`, `first_level_item`, `second_level_item`, `third_level_item`, `scope`, `sort`, `delete_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (28, 1, 2, '保密费', 1, 28, 0, 0, sysdate(), 0, sysdate());
INSERT INTO `salary_item`(`salary_item_id`, `first_level_item`, `second_level_item`, `third_level_item`, `scope`, `sort`, `delete_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (29, 1, 2, '回款提成', 1, 29, 0, 0, sysdate(), 0, sysdate());
INSERT INTO `salary_item`(`salary_item_id`, `first_level_item`, `second_level_item`, `third_level_item`, `scope`, `sort`, `delete_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (30, 1, 2, '其他津贴', 1, 30, 0, 0, sysdate(), 0, sysdate());
INSERT INTO `salary_item`(`salary_item_id`, `first_level_item`, `second_level_item`, `third_level_item`, `scope`, `sort`, `delete_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (31, 1, 3, '房补', 1, 31, 0, 0, sysdate(), 0, sysdate());
INSERT INTO `salary_item`(`salary_item_id`, `first_level_item`, `second_level_item`, `third_level_item`, `scope`, `sort`, `delete_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (32, 1, 3, '餐补', 1, 32, 0, 0, sysdate(), 0, sysdate());
INSERT INTO `salary_item`(`salary_item_id`, `first_level_item`, `second_level_item`, `third_level_item`, `scope`, `sort`, `delete_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (33, 1, 3, '学历证', 1, 33, 0, 0, sysdate(), 0, sysdate());
INSERT INTO `salary_item`(`salary_item_id`, `first_level_item`, `second_level_item`, `third_level_item`, `scope`, `sort`, `delete_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (34, 1, 3, '短号补贴', 1, 34, 0, 0, sysdate(), 0, sysdate());
INSERT INTO `salary_item`(`salary_item_id`, `first_level_item`, `second_level_item`, `third_level_item`, `scope`, `sort`, `delete_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (35, 1, 3, '全勤奖', 1, 35, 0, 0, sysdate(), 0, sysdate());
INSERT INTO `salary_item`(`salary_item_id`, `first_level_item`, `second_level_item`, `third_level_item`, `scope`, `sort`, `delete_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (36, 1, 3, '年资', 1, 36, 0, 0, sysdate(), 0, sysdate());
INSERT INTO `salary_item`(`salary_item_id`, `first_level_item`, `second_level_item`, `third_level_item`, `scope`, `sort`, `delete_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (37, 1, 3, '证书补贴', 1, 37, 0, 0, sysdate(), 0, sysdate());
INSERT INTO `salary_item`(`salary_item_id`, `first_level_item`, `second_level_item`, `third_level_item`, `scope`, `sort`, `delete_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (38, 1, 3, '电工证', 1, 38, 0, 0, sysdate(), 0, sysdate());
INSERT INTO `salary_item`(`salary_item_id`, `first_level_item`, `second_level_item`, `third_level_item`, `scope`, `sort`, `delete_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (39, 1, 3, '其他福利', 1, 39, 0, 0, sysdate(), 0, sysdate());
INSERT INTO `salary_item`(`salary_item_id`, `first_level_item`, `second_level_item`, `third_level_item`, `scope`, `sort`, `delete_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (40, 2, 4, '战略奖', 2, 40, 0, 0, sysdate(), 0, sysdate());
INSERT INTO `salary_item`(`salary_item_id`, `first_level_item`, `second_level_item`, `third_level_item`, `scope`, `sort`, `delete_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (41, 2, 4, '项目奖', 1, 41, 0, 0, sysdate(), 0, sysdate());
INSERT INTO `salary_item`(`salary_item_id`, `first_level_item`, `second_level_item`, `third_level_item`, `scope`, `sort`, `delete_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (42, 2, 4, '绩效奖金', 1, 42, 0, 0, sysdate(), 0, sysdate());
INSERT INTO `salary_item`(`salary_item_id`, `first_level_item`, `second_level_item`, `third_level_item`, `scope`, `sort`, `delete_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (43, 3, 5, '社保', 1, 43, 0, 0, sysdate(), 0, sysdate());
INSERT INTO `salary_item`(`salary_item_id`, `first_level_item`, `second_level_item`, `third_level_item`, `scope`, `sort`, `delete_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (44, 3, 5, '公积金', 1, 44, 0, 0, sysdate(), 0, sysdate());
INSERT INTO `salary_item`(`salary_item_id`, `first_level_item`, `second_level_item`, `third_level_item`, `scope`, `sort`, `delete_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (45, 3, 5, '个税', 1, 45, 0, 0, sysdate(), 0, sysdate());
INSERT INTO `salary_item`(`salary_item_id`, `first_level_item`, `second_level_item`, `third_level_item`, `scope`, `sort`, `delete_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (46, 3, 6, '水电费', 1, 46, 0, 0, sysdate(), 0, sysdate());
INSERT INTO `salary_item`(`salary_item_id`, `first_level_item`, `second_level_item`, `third_level_item`, `scope`, `sort`, `delete_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (47, 3, 6, '餐费', 1, 47, 0, 0, sysdate(), 0, sysdate());
INSERT INTO `salary_item`(`salary_item_id`, `first_level_item`, `second_level_item`, `third_level_item`, `scope`, `sort`, `delete_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (48, 3, 6, '请假', 1, 48, 0, 0, sysdate(), 0, sysdate());
INSERT INTO `salary_item`(`salary_item_id`, `first_level_item`, `second_level_item`, `third_level_item`, `scope`, `sort`, `delete_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (49, 3, 6, '其他扣款', 1, 49, 0, 0, sysdate(), 0, sysdate());
