USE `system_manage`;
SET NAMES utf8mb4;
-- ----------------------------
-- menu update
-- ----------------------------
INSERT INTO menu (menu_id, parent_menu_id, menu_type, menu_name, product_package_id, sort, `path`, component, query, external_link_flag, cache_flag, visible_flag, permission_code, icon, status, delete_flag, create_by, create_time, update_by, update_time) VALUES(366, 0, 1, '战略云', 3, 3, 'stratage', NULL, NULL, 0, 0, 1, NULL, 'transparent', 1, 0, 1, sysdate(), 1, sysdate());
INSERT INTO menu (menu_id, parent_menu_id, menu_type, menu_name, product_package_id, sort, `path`, component, query, external_link_flag, cache_flag, visible_flag, permission_code, icon, status, delete_flag, create_by, create_time, update_by, update_time) VALUES(367, 366, 2, '差距分析', 3, 1, 'gap', '/stratage/', NULL, 0, 0, 1, NULL, 'transparent', 1, 1, 1, sysdate(), 1, sysdate());
INSERT INTO menu (menu_id, parent_menu_id, menu_type, menu_name, product_package_id, sort, `path`, component, query, external_link_flag, cache_flag, visible_flag, permission_code, icon, status, delete_flag, create_by, create_time, update_by, update_time) VALUES(368, 366, 1, '差距分析', 1, 1, 'gap', NULL, NULL, 0, 0, 1, NULL, 'chajufenxi', 1, 0, 1, sysdate(), 1, sysdate());
INSERT INTO menu (menu_id, parent_menu_id, menu_type, menu_name, product_package_id, sort, `path`, component, query, external_link_flag, cache_flag, visible_flag, permission_code, icon, status, delete_flag, create_by, create_time, update_by, update_time) VALUES(369, 368, 2, '差距分析', 3, 1, 'gapAnalysis', 'stratage/gap/gapAnalysis/index', NULL, 0, 0, 1, NULL, 'transparent', 1, 0, 1, sysdate(), 1, sysdate());
INSERT INTO menu (menu_id, parent_menu_id, menu_type, menu_name, product_package_id, sort, `path`, component, query, external_link_flag, cache_flag, visible_flag, permission_code, icon, status, delete_flag, create_by, create_time, update_by, update_time) VALUES(370, 366, 1, '市场洞察', 3, 2, 'marketInsight', NULL, NULL, 0, 0, 1, NULL, 'shichangdongcha', 1, 0, 1, sysdate(), 1, sysdate());
INSERT INTO menu (menu_id, parent_menu_id, menu_type, menu_name, product_package_id, sort, `path`, component, query, external_link_flag, cache_flag, visible_flag, permission_code, icon, status, delete_flag, create_by, create_time, update_by, update_time) VALUES(371, 370, 2, '看宏观', 3, 1, 'lookMacro', 'marketInsight/lookMacro/index', NULL, 0, 0, 1, NULL, NULL, 1, 0, 1, sysdate(), 1, sysdate());
INSERT INTO menu (menu_id, parent_menu_id, menu_type, menu_name, product_package_id, sort, `path`, component, query, external_link_flag, cache_flag, visible_flag, permission_code, icon, status, delete_flag, create_by, create_time, update_by, update_time) VALUES(372, 370, 2, '看行业', 3, 2, 'lookIndustry', 'marketInsight/lookIndustry/index', NULL, 0, 0, 1, NULL, NULL, 1, 0, 1, sysdate(), 1, sysdate());
INSERT INTO menu (menu_id, parent_menu_id, menu_type, menu_name, product_package_id, sort, `path`, component, query, external_link_flag, cache_flag, visible_flag, permission_code, icon, status, delete_flag, create_by, create_time, update_by, update_time) VALUES(373, 370, 2, '看客户', 3, 3, 'lookCustomer', 'marketInsight/lookCustomer/index', NULL, 0, 0, 1, NULL, 'transparent', 1, 0, 1, sysdate(), 1, sysdate());
INSERT INTO menu (menu_id, parent_menu_id, menu_type, menu_name, product_package_id, sort, `path`, component, query, external_link_flag, cache_flag, visible_flag, permission_code, icon, status, delete_flag, create_by, create_time, update_by, update_time) VALUES(374, 370, 2, '看对手', 3, 4, 'lookOpponent', 'marketInsight/lookOpponent/index', NULL, 0, 0, 1, NULL, 'transparent', 1, 0, 1, sysdate(), 1, sysdate());
INSERT INTO menu (menu_id, parent_menu_id, menu_type, menu_name, product_package_id, sort, `path`, component, query, external_link_flag, cache_flag, visible_flag, permission_code, icon, status, delete_flag, create_by, create_time, update_by, update_time) VALUES(375, 370, 2, '看自身', 3, 5, 'lookSelf', 'marketInsight/lookSelf/index', NULL, 0, 0, 1, NULL, 'transparent', 1, 0, 1, sysdate(), 1, sysdate());
INSERT INTO menu (menu_id, parent_menu_id, menu_type, menu_name, product_package_id, sort, `path`, component, query, external_link_flag, cache_flag, visible_flag, permission_code, icon, status, delete_flag, create_by, create_time, update_by, update_time) VALUES(376, 366, 1, '战略意图', 3, 3, 'intent', NULL, NULL, 0, 0, 1, NULL, NULL, 1, 0, 1, sysdate(), 1, sysdate());
INSERT INTO menu (menu_id, parent_menu_id, menu_type, menu_name, product_package_id, sort, `path`, component, query, external_link_flag, cache_flag, visible_flag, permission_code, icon, status, delete_flag, create_by, create_time, update_by, update_time) VALUES(377, 376, 2, '战略意图', 3, 1, 'strategeIntent', 'intent/strategeIntent/index', NULL, 0, 0, 1, NULL, 'transparent', 1, 0, 1, sysdate(), 1, sysdate());
INSERT INTO menu (menu_id, parent_menu_id, menu_type, menu_name, product_package_id, sort, `path`, component, query, external_link_flag, cache_flag, visible_flag, permission_code, icon, status, delete_flag, create_by, create_time, update_by, update_time) VALUES(378, 366, 1, '业务设计', 3, 4, 'business', NULL, NULL, 0, 0, 1, NULL, 'yewusheji', 1, 0, 1, sysdate(), 1, sysdate());
INSERT INTO menu (menu_id, parent_menu_id, menu_type, menu_name, product_package_id, sort, `path`, component, query, external_link_flag, cache_flag, visible_flag, permission_code, icon, status, delete_flag, create_by, create_time, update_by, update_time) VALUES(379, 378, 2, '业务设计', 3, 1, 'businessDesign', 'business/businessDesign/index', NULL, 0, 0, 1, NULL, 'transparent', 1, 0, 1, sysdate(), 1, sysdate());
INSERT INTO menu (menu_id, parent_menu_id, menu_type, menu_name, product_package_id, sort, `path`, component, query, external_link_flag, cache_flag, visible_flag, permission_code, icon, status, delete_flag, create_by, create_time, update_by, update_time) VALUES(380, 366, 1, '战略解码', 3, 5, 'stratageDecode', NULL, NULL, 0, 0, 1, NULL, NULL, 1, 0, 1, sysdate(), 1, sysdate());
INSERT INTO menu (menu_id, parent_menu_id, menu_type, menu_name, product_package_id, sort, `path`, component, query, external_link_flag, cache_flag, visible_flag, permission_code, icon, status, delete_flag, create_by, create_time, update_by, update_time) VALUES(381, 4, 1, '战略云配置', 3, 5, 'stratage', NULL, NULL, 0, 0, 1, NULL, 'transparent', 1, 0, 1, sysdate(), 1, sysdate());
INSERT INTO menu (menu_id, parent_menu_id, menu_type, menu_name, product_package_id, sort, `path`, component, query, external_link_flag, cache_flag, visible_flag, permission_code, icon, status, delete_flag, create_by, create_time, update_by, update_time) VALUES(382, 381, 2, '规划业务单元配置', 3, 1, 'planBusinessUnit', 'setting/stratage/planBusinessUnit/index', NULL, 0, 0, 1, NULL, 'transparent', 1, 0, 1, sysdate(), 1, sysdate());
INSERT INTO menu (menu_id, parent_menu_id, menu_type, menu_name, product_package_id, sort, `path`, component, query, external_link_flag, cache_flag, visible_flag, permission_code, icon, status, delete_flag, create_by, create_time, update_by, update_time) VALUES(383, 382, 2, '规划业务单元配置新增', 3, 1, 'planBusinessUnitAdd', 'setting/stratage/planBusinessUnit/components/add', NULL, 0, 1, 0, NULL, 'transparent', 1, 0, 1, sysdate(), 1, sysdate());
INSERT INTO menu (menu_id, parent_menu_id, menu_type, menu_name, product_package_id, sort, `path`, component, query, external_link_flag, cache_flag, visible_flag, permission_code, icon, status, delete_flag, create_by, create_time, update_by, update_time) VALUES(384, 382, 2, '规划业务单元配置编辑', 3, 2, 'planBusinessUnitEdit', 'setting/stratage/planBusinessUnit/components/edit', NULL, 0, 1, 0, NULL, 'transparent', 1, 0, 1, sysdate(), 1, sysdate());
INSERT INTO menu (menu_id, parent_menu_id, menu_type, menu_name, product_package_id, sort, `path`, component, query, external_link_flag, cache_flag, visible_flag, permission_code, icon, status, delete_flag, create_by, create_time, update_by, update_time) VALUES(385, 382, 2, '规划业务单元配置详情', 3, 3, 'planBusinessUnitDetail', 'setting/stratage/planBusinessUnit/components/detail', NULL, 0, 0, 0, NULL, 'transparent', 1, 0, 1, sysdate(), 1, sysdate());
INSERT INTO menu (menu_id, parent_menu_id, menu_type, menu_name, product_package_id, sort, `path`, component, query, external_link_flag, cache_flag, visible_flag, permission_code, icon, status, delete_flag, create_by, create_time, update_by, update_time) VALUES(386, 3, 2, '仪表盘', 1, 0, 'manageHome', 'manage/home/index', NULL, 0, 0, 1, 'operate:cloud:dashboard', 'yibiaopan', 1, 0, 1, sysdate(), 1, sysdate());
INSERT INTO menu (menu_id, parent_menu_id, menu_type, menu_name, product_package_id, sort, `path`, component, query, external_link_flag, cache_flag, visible_flag, permission_code, icon, status, delete_flag, create_by, create_time, update_by, update_time) VALUES(387, 386, 3, '关键经营指标仪表盘', 1, 0, NULL, NULL, NULL, 0, 0, 1, 'operate:cloud:dashboard:target', NULL, 1, 0, 1, sysdate(), 1, sysdate());