USE `system_manage`;
SET NAMES utf8mb4;
-- ----------------------------
-- menu update
-- ----------------------------
INSERT INTO menu (menu_id, parent_menu_id, menu_type, menu_name, product_package_id, sort, `path`, component, query, external_link_flag, cache_flag, visible_flag, permission_code, icon, status, delete_flag, create_by, create_time, update_by, update_time) VALUES(388, 382, 3, '删除', 3, 4, NULL, NULL, NULL, 0, 0, 1, 'strategy:cloud:planBusinessUnit:remove', NULL, 1, 0, 1, sysdate(), 1, sysdate());
INSERT INTO menu (menu_id, parent_menu_id, menu_type, menu_name, product_package_id, sort, `path`, component, query, external_link_flag, cache_flag, visible_flag, permission_code, icon, status, delete_flag, create_by, create_time, update_by, update_time) VALUES(389, 381, 2, '行业吸引力配置', 3, 2, 'industryAttraction', 'setting/stratage/industryAttraction/index', NULL, 0, 0, 1, 'strategy:cloud:industryAttraction:pageList', 'transparent', 1, 0, 1, sysdate(), 1, sysdate());
INSERT INTO menu (menu_id, parent_menu_id, menu_type, menu_name, product_package_id, sort, `path`, component, query, external_link_flag, cache_flag, visible_flag, permission_code, icon, status, delete_flag, create_by, create_time, update_by, update_time) VALUES(390, 389, 2, '行业吸引力配置新增', 3, 1, 'industryAttractionAdd', 'setting/stratage/industryAttraction/components/add', NULL, 0, 1, 0, 'strategy:cloud:industryAttraction:add', 'transparent', 1, 0, 1, sysdate(), 1, sysdate());
INSERT INTO menu (menu_id, parent_menu_id, menu_type, menu_name, product_package_id, sort, `path`, component, query, external_link_flag, cache_flag, visible_flag, permission_code, icon, status, delete_flag, create_by, create_time, update_by, update_time) VALUES(391, 389, 2, '行业吸引力配置编辑', 3, 2, 'industryAttractionEdit', 'setting/stratage/industryAttraction/components/edit', NULL, 0, 1, 0, 'strategy:cloud:industryAttraction:edit', 'transparent', 1, 0, 1, sysdate(), 1, sysdate());
INSERT INTO menu (menu_id, parent_menu_id, menu_type, menu_name, product_package_id, sort, `path`, component, query, external_link_flag, cache_flag, visible_flag, permission_code, icon, status, delete_flag, create_by, create_time, update_by, update_time) VALUES(392, 389, 2, '行业吸引力配置详情', 3, 3, 'industryAttractionDetail', 'setting/stratage/industryAttraction/components/detail', NULL, 0, 0, 0, 'strategy:cloud:industryAttraction:info', 'transparent', 1, 0, 1, sysdate(), 1, sysdate());
INSERT INTO menu (menu_id, parent_menu_id, menu_type, menu_name, product_package_id, sort, `path`, component, query, external_link_flag, cache_flag, visible_flag, permission_code, icon, status, delete_flag, create_by, create_time, update_by, update_time) VALUES(393, 389, 3, '删除', 3, 4, NULL, NULL, NULL, 0, 0, 1, 'strategy:cloud:industryAttraction:remove', NULL, 1, 0, 1, sysdate(), 1, sysdate());